version: "3"
services:
  # Database
  database:
    image: postgres:12.2-alpine
    container_name: alliodesk-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./database/datas:/var/lib/postgresql
    ports:
      - 5432:5432
  # API
  api:
    build: ./api
    container_name: alliodesk-api
    ports:
      - 3456:3456
    depends_on:
      - database
