version: "3"
services:
  # Database
  database:
    build: ./database
    image: alliodesk-db:$DATABASE_VERSION
    container_name: alliodesk-db
    environment:
      - DATABASE_VERSION=${DATABASE_VERSION}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
  # API
  api:
    build: ./api
    image: alliodesk-api:$API_VERSION
    container_name: alliodesk-api
    environment:
      - API_VERSION=${API_VERSION}
    ports:
      - 3456:3456
    depends_on:
      - database
  # Frontend (Angular)
  frontend:
    build: ./frontend
    image: alliodesk-frontend:$FRONTEND_VERSION
    container_name: alliodesk-frontend
    environment:
      - FRONTEND_VERSION=${FRONTEND_VERSION}
      - PORT=80
    ports:
      - 8765:80
    depends_on:
      - api
  # Client (java)
  client:
    build: ./client
    image: alliodesk-client:$CLIENT_VERSION
    container_name: alliodesk-client
    environment:
      - CLIENT_VERSION=${CLIENT_VERSION}
    ports:
      - 8430:8360
    depends_on:
      - api
