version: "3"
services:
  # Database (Postgres)
  alliodesk-db:
    image: postgres:12.2-alpine
    container_name: alliodesk-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./database/datas:/var/lib/postgresql
    ports:
      - 5432:5432
