name: CD API - Deploy
on:
  push:
    branches:
      - 'master'
      - 'feature/**' # TODO: remove this line after testings...
    #paths:
    #  - 'api/**'

env:
  API_IMAGE_NAME: alliodesk-api
  API_IMAGE_VERSION_LATEST: latest
  HEROKU_APP_NAME_BACK: ${{ secrets.HEROKU_APP_NAME_BACK }}
  HUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  HUB_PROJECT: ${{ secrets.HUB_PROJECT }}
  HUB_REGISTRY: ${{ secrets.HUB_REGISTRY }}
  HUB_USERNAME: ${{ secrets.HUB_USERNAME }}

jobs:
  # DEPLOY TO GITHUB PACKAGES
  deploy-github:
    runs-on: ubuntu-latest
    env:
      API_VERSION_FILE: ./api/package.json
    steps:
      - uses: actions/checkout@v2
      - name: Login to Github Packages
        run: docker login -u $HUB_USERNAME -p $HUB_PASSWORD $HUB_REGISTRY
      - name: Build a docker image of API
        run: |
          version=`sed -nE 's/^\s*"version": "(.*?)",$/\1/p' $API_VERSION_FILE`

          echo "Building docker image of $API_IMAGE_NAME version $version..."
          docker build -t "$HUB_REGISTRY/$HUB_USERNAME/$HUB_PROJECT/$API_IMAGE_NAME:$version" ./api
          echo "SUCCESS\n"
      - name: Push to Github Packages
        run: |
          version=`sed -nE 's/^\s*"version": "(.*?)",$/\1/p' $API_VERSION_FILE`

          echo "Pushing docker image of $API_IMAGE_NAME version $version..."
          docker push "$HUB_REGISTRY/$HUB_USERNAME/$HUB_PROJECT/$API_IMAGE_NAME:$version"
          echo "SUCCESS\n"

          echo "Pushing docker image of $API_IMAGE_NAME version $API_IMAGE_VERSION_LATEST..."
          docker tag "$HUB_REGISTRY/$HUB_USERNAME/$HUB_PROJECT/$API_IMAGE_NAME:$version" \
                  "$HUB_REGISTRY/$HUB_USERNAME/$HUB_PROJECT/$API_IMAGE_NAME:$API_IMAGE_VERSION_LATEST"
          docker push "$HUB_REGISTRY/$HUB_USERNAME/$HUB_PROJECT/$API_IMAGE_NAME:$API_IMAGE_VERSION_LATEST"
          echo "SUCCESS\n"
      - name: Logout from Github Packages
        run: docker logout $HUB_REGISTRY
  # DEPLOY TO HEROKU REGISTRY
  deploy-heroku:
    runs-on: ubuntu-latest
    needs: deploy-github
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_PROCESS_TYPE: web
      HEROKU_REGISTRY: ${{ secrets.HEROKU_REGISTRY }}
    steps:
      - uses: actions/checkout@v2
      - name: Login to Github Packages
        run: docker login $HUB_REGISTRY -u $HUB_USERNAME -p $HUB_PASSWORD
      - name: Docker pull latest image from Github Packages
        run: |
          echo "Pulling docker image $API_IMAGE_NAME:$API_IMAGE_VERSION_LATEST from Github Packages..."
          docker pull "$HUB_REGISTRY/$HUB_USERNAME/$HUB_PROJECT/$API_IMAGE_NAME:$API_IMAGE_VERSION_LATEST"
          echo "SUCCESS\n"
      - name: Logout from Github Packages
        run: docker logout $HUB_REGISTRY
      - name: Login to Heroku Registry
        run: docker login -u _ -p $HEROKU_API_KEY $HEROKU_REGISTRY
      - name: Tag pulled image of API
        run: |
          echo "Building docker image of $HEROKU_PROCESS_TYPE..."
          docker tag "$HUB_REGISTRY/$HUB_USERNAME/$HUB_PROJECT/$API_IMAGE_NAME:$API_IMAGE_VERSION_LATEST" \
                  "$HEROKU_REGISTRY/$HEROKU_APP_NAME_BACK/$HEROKU_PROCESS_TYPE"
          echo "SUCCESS\n"
      - name: Push an image to Heroku
        run: |
          echo "Pushing docker image of $HEROKU_PROCESS_TYPE..."
          docker push "$HEROKU_REGISTRY/$HEROKU_APP_NAME_BACK/$HEROKU_PROCESS_TYPE"
          echo "SUCCESS\n"
      - name: Logout from Heroku Registry
        run: docker logout $HEROKU_REGISTRY
