name: CD Client - Deploy
on:
  push:
    branches:
      - 'master'
    paths:
      - 'client/**'

env:
  CLIENT_MODULE_PATH: ./client

jobs:
  # TAG THE RELEASE ON GITHUB
  tag-release:
    runs-on: ubuntu-latest
    env:
      GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
      GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
    steps:
      - uses: actions/checkout@v2
      - name: Set identity
        run: |
          git config user.email "$GIT_USER_EMAIL"
          git config user.name "$GIT_USER_NAME"
      - name: Create tag
        run: |
          version=`cat $CLIENT_MODULE_PATH/VERSION`

          echo "Creating tag for Client version $version..."
          git tag -a "client-$version" -m "Release Client version $version"
          echo "SUCCESS\n"
      - name: Push tag to Github
        run: git push --tags origin
