name: CI API - Testings
on:
  pull_request:
    branches:
      - 'master'
      - 'develop'
    paths:
      - 'api/**'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node JS 12.16.1
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.1
      - name: Install all dependencies
        run: |
          cd ./api
          npm clean-install
      - name: Run unit tests
        run: |
          cd ./api
          npm run unit-test
  integration-tests:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node JS 12.16.1
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.1
      - name: Install all dependencies
        run: |
          cd ./api
          npm clean-install
      - name: Run integration tests
        run: |
          cd ./api
          npm run integration-test
