name: CI Client - Unit Test & Build
on:
  pull_request:
    branches:
      - 'master'
      - 'develop'
    paths:
      - 'client/**'

env:
  CLIENT_MODULE_PATH: ./client

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11.0.6'
          java-package: jdk
      - name: Run unit tests
        run: |
           cd $CLIENT_MODULE_PATH
           mvn clean test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11.0.6'
          java-package: jdk
      - name: Build client
        run: |
          cd $CLIENT_MODULE_PATH
          mvn clean package
