name: CI Client - Unit Test
on:
  push:
    branches:
      - 'feature/**'
      - 'release/**'
      - 'hotfix/**'
    paths:
      - 'client/**'
  pull_request:
    branches:
      - develop
    paths:
      - 'client/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
          with:
            java-version: '11.0.6'
            java-package: jdk
            architecture: x64
      - uses: actions/checkout@v2
        - name: Build client
          run: |
             cd ./client
             mvn -B package --file pom.xml
